# Generated by Django 3.1 on 2020-11-14 10:48

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=3)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categorys',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, max_length=2000, null=True, upload_to='')),
                ('rating', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('teacher', models.CharField(blank=True, max_length=300, null=True)),
                ('theme', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Courses.category')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Explanation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('explain', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='')),
                ('video', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Explanation',
                'verbose_name_plural': 'Explanations',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Content', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Suggestion',
                'verbose_name_plural': 'Suggestions',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.IntegerField(blank=True, default='1', null=True)),
                ('lesson_name', models.CharField(blank=True, max_length=255, null=True)),
                ('document', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('video', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('course_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.course')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('add', models.FileField(blank=True, null=True, upload_to='')),
                ('solution', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('explanation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.explanation')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.lesson')),
                ('suggestions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.suggestion')),
            ],
        ),
    ]
