# Generated by Django 3.1 on 2020-11-22 15:20

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0003_auto_20201122_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='question',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='explanation',
            name='explain',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='document',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
