# Generated by Django 3.1 on 2020-11-27 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0004_auto_20201122_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='suggestions',
        ),
        migrations.AddField(
            model_name='choices',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Courses.activity'),
        ),
        migrations.AddField(
            model_name='explanation',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Courses.activity'),
        ),
    ]
